channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==24.3.1
  - pip:
    - accelerate==1.2.1
    - peft==0.14.0
    - flash-attn==2.3.2
    - bitsandbytes==0.45.0
    - transformers==4.48.0
    - trl==0.13.0
    - scipy==1.14.1
    - azureml-mlflow==1.58.0.post3
    - deepspeed==0.15.4
 
 


