channels:  
  - conda-forge  
  - defaults  
dependencies:  
  - python=3.11  
  - pip  
  - pip:  
      - ray[default]==2.9.0  
      - azure-storage-blob  
      - azureml-mlflow
      - azureml-defaults
      - azure-identity  

