$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: vllm-custom
endpoint_name: llma2-fine-tuning
model: azureml:llama2_13b_chat_sql_tuned:4 #replace this with your model name and version
model_mount_path: /models # mount to /models path, so model will show up llama2_13b_chat_sql_tuned 
environment_variables:
  MODEL_PATH: /models/llama2_13b_chat_sql_tuned/artifacts/trained_model # this will need to be set, so vLLM knows where to find the model
  VLLM_ARGS: ""
environment:
  image: cf406cec7620485598800b18191dabd0.azurecr.io/azureml/azureml_96f36f591e5347e2e72d1ddab8ea7dd8
  inference_config:
    liveness_route:
      port: 8000
      path: /health
    readiness_route:
      port: 8000
      path: /health
    scoring_route:
      port: 8000
      path: /
instance_type: Standard_NC24ads_A100_v4
instance_count: 1
request_settings:
    max_concurrent_requests_per_instance: 1
    request_timeout_ms: 10000
liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 30
readiness_probe:
  initial_delay: 120
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 30
