$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: llma2-fine-tuning
model: azureml:llama2_13b_chat_sql_tuned:4 #replace this with your model name and version
# model: azureml://registries/azureml-meta/models/Llama-2-7b-chat/versions/12
code_configuration:
  code: ./
  scoring_script: score_chat.py
environment: 
  image: mcr.microsoft.com/azureml/curated/foundation-model-inference:6
instance_type: standard_nc24ads_a100_v4
instance_count: 1
request_settings:
    request_timeout_ms: 60000
    max_concurrent_requests_per_instance: 2