$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: unsloth_pipeline_with_hyperparameter_sweep
description: Tune hyperparameters for pretrain then continue with fine-tunning
settings:
    default_compute: azureml:NC96adsA100 #update NC48adsA100 to the name of your compute target 
jobs:
  pretrain_step:
    type: sweep
    sampling_algorithm: bayesian
    search_space:
      learning_rate:
        type: uniform
        min_value: 5e-5
        max_value: 5e-3
    objective:
      goal: minimize
      primary_metric: perplexity
    limits:
      max_total_trials: 1
      max_concurrent_trials: 1
      timeout: 3600
    inputs:
      mounted_data_folder:
        type: uri_folder
        mode: ro_mount
        path: azureml:test_data:1
    outputs:
      trained_model:
    trial: ./pretrain.yml
  fine_tune_step:
    type: command
    inputs:
      trained_model: ${{parent.jobs.pretrain_step.outputs.trained_model}}
    outputs:
      fine_tuned_model:
    component: ./fine_tune.yml

    